name: Nightly Build and Push

on: push
#on:
#  schedule:
#  - cron: "0 0 * * *"
#  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@master
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build All
      run: |
        ./build_all.sh
